@startuml
namespace at.reder.railcom.datamodel {
    interface Entity {
        getId() : int
        getName() : String
        setName(name : String)
        getDescription() : String
        setDescription(description : String)
    }


}

namespace at.reder.railcom.datamodel.rail {

    interface RailwayEntity {
        getWheelTrack() : int
        setWheelTrack(wheelTrack : int)
        getRailwayAgency() : String
        setRailwayAgency(railwayAgency : String)
        getMass() : int
        setMass(mass : int)
    }

    at.reder.railcom.datamodel.Entity <-- RailwayEntity

    interface Locomotive {
        getWheelArrangement() : String
        setWheelArrangement(wheelArrangement : String)
        setOperatingMode(operatingMode : OperatingMode)
    }

    RailwayEntity <-- Locomotive

    interface SteamLocomotive {
    }

    Locomotive <-- SteamLocomotive

    interface DieselLocomotive {
    }

    Locomotive <-- DieselLocomotive

    interface ElectricLocomotive {
    }

    Locomotive <-- ElectricLocomotive

    interface Wagon {
        getAxisCount() : int
        setAxisCount(axisCount : int)
    }


    RailwayEntity <-- Wagon


    interface Train {
        getTrain() : List<RailwayEntity>
        addEntity(pos : int, entity : RailwayEntity)
    }

    Train "1" *-- "*" RailwayEntity

}

namespace at.reder.railcom.datamodel.track {

    interface Signal {
    }

    at.reder.railcom.datamodel.Entity <-- Signal

    interface Turnout {
    }

    at.reder.railcom.datamodel.Entity <-- Turnout

    interface Platform {
    }

    at.reder.railcom.datamodel.Entity <-- Platform

    interface BlockPost {
    }

    at.reder.railcom.datamodel.Entity <-- BlockPost
}

namespace at.reder.railcom.datamodel.street {

    interface StreetEntity {
    }

    at.reder.railcom.datamodel.Entity <-- StreetEntity

}

namespace at.reder.railcom.datamodel.building {

    interface HouseEntity {
    }

    at.reder.railcom.datamodel.Entity <-- HouseEntity
}
@enduml
